"""add name column

Revision ID: 122462fb7deb
Revises: cad175ef45d6
Create Date: 2021-02-22 11:50:39.266675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122462fb7deb'
down_revision = 'cad175ef45d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_unique_constraint("projects_name_key", 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projects_name_key", 'projects', type_='unique')
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###
